# Generated by Django 2.0.1 on 2018-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.CharField(max_length=30, blank=True)),
                ('celebracao', models.CharField(max_length=150)),
                ('hoje_minha_decisao_foi', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.CharField(max_length=30, blank=True)),
                ('idade', models.CharField(max_length=30, blank=True)),
                ('cpf', models.CharField(max_length=30, blank=True)),
                ('profissao', models.CharField(max_length=30, blank=True)),
                ('email', models.CharField(max_length=30, blank=True)),
                ('endereco', models.CharField(max_length=150, blank=True)),
                ('compl', models.CharField(max_length=30, blank=True)),
                ('bairro', models.CharField(max_length=30, blank=True)),
                ('cidade', models.CharField(max_length=30, blank=True)),
                ('estado', models.CharField(max_length=2)),
                ('celular_whatsapp', models.CharField(max_length=30, blank=True)),
                ('campus', models.CharField(max_length=30, blank=True)),
                ('tipo_de_preenchimento', models.CharField(max_length=150)),
                ('nome_atendente', models.CharField(max_length=30, blank=True)),
                ('codigo_membro_ic', models.CharField(max_length=30, blank=True)),
                ('supervisor', models.CharField(max_length=30, blank=True)),
                ('email_membro', models.CharField(max_length=30, blank=True)),
                ('celular_membro_whatsapp', models.CharField(max_length=30, blank=True)),
                ('discipulador_pessoal', models.CharField(max_length=3)),
                ('coordenador_recomeco', models.CharField(max_length=30, blank=True)),
                ('supervisor_recomeco', models.CharField(max_length=30, blank=True)),
            ],
        ),
    ]
