# Generated by Django 3.2.9 on 2021-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_auto_20180210_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='celebracao',
            field=models.CharField(choices=[('Dominical', 'Dominical'), ('Eleve', 'Eleve'), ('Juniores', 'Juniores'), ('Outros', 'Outros')], max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='discipulador_pessoal',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='hoje_minha_decisao_foi',
            field=models.CharField(choices=[('Aceitar a Jesus Cristo como Salvador', 'Aceitar a Jesus Cristo como Salvador'), ('Reconciliar-me com Cristo e a Igreja', 'Reconciliar-me com Cristo e a Igreja'), ('Ser batizado em águas', 'Ser batizado em águas')], max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='tipo_de_preenchimento',
            field=models.CharField(choices=[('Cartão preenchido pelo decidido', 'Cartão preenchido pelo decidido'), ('Cartão preenchido em atendimento', 'Cartão preenchido em atendimento')], max_length=150),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
